package com.projeto.doe_facil.utils.enums;

public enum ItemCategory {
    CLOTHING_ACCESSORIES,
    FOOTWEAR,
    FURNITURE,
    ELECTRONICS_APPLIANCES,
    BOOKS_EDUCATIONAL_MATERIALS,
    TOYS_GAMES,
    KITCHEN_UTENSILS,
    OFFICE_SCHOOL_SUPPLIES,
    PERSONAL_CARE_PRODUCTS,
    SPORTS_LEISURE_ITEMS
}
